apps/courses/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'geda'
__date__ = '2020/2/6 14:28'

from django.urls import path
from .views import CourseListView, CourseDetailView, CourseCommentView, CourseVideoView, AddCommentView, VideoPlayView

urlpatterns = [
	path('list/', CourseListView.as_view(), name='course_list'),
	path('detail/<int:course_id>/', CourseDetailView.as_view(), name='course_detail'),
	path('info/<int:course_id>/', CourseVideoView.as_view(), name='course_info'),
	path('comment/<int:course_id>/', CourseCommentView.as_view(), name='course_comment'),
	path('video/<int:video_id>/', VideoPlayView.as_view(), name='video_play'),
	path('add_comment/', AddCommentView.as_view(), name='add_comment'),

]

apps/organization/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'geda'
__date__ = '2020/2/3 17:47'

from django.urls import path

from .views import OrgListView, AddAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeachersView, UserFavView, \
					TeacherListView, TeacherDetailView

urlpatterns = [
	# 机构url 管理
	path('list/', OrgListView.as_view(), name='org_list'),
	path('addask/', AddAskView.as_view(), name='add_ask'),
	path('org_home/<int:org_id>/', OrgHomeView.as_view(), name='org_home'),
	path('org_course/<int:org_id>/', OrgCourseView.as_view(), name='org_course'),
	path('org_desc/<int:org_id>/', OrgDescView.as_view(), name='org_desc'),
	path('org_teacher/<int:org_id>/', OrgTeachersView.as_view(), name='org_teacher'),
	path('add_fav/', UserFavView.as_view(), name='add_fav'),

	# 讲师url 管理
	path('teacher/list/', TeacherListView.as_view(), name='teacher_list'),
	path('teacher_detail/<int:teacher_id>/', TeacherDetailView.as_view(), name='teacher_detail')
]

apps/users/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'geda'
__date__ = '2020/2/3 10:50'

from django.urls import path

from .views import LoginView, LogoutView, RegisterView, RegisterActiveView, ResetPsdView, ForgetpwdView, ModifyPsdView
from .views import UserInfoView, UpdatePwdView, SendEmailCodeView, UpdateEmailView, UpdateUserProfileView , UploadImageView
from .views import MycourseView, MyFavOrgView, MyFavCourseView, MyFavTeacherView, UserMessageView

urlpatterns = [
	path("login/", LoginView.as_view(), name='login'),
	path("logout/", LogoutView.as_view(), name='logout'),
	path("register/", RegisterView.as_view(), name='register'),
	path('active/<url_active_code>', RegisterActiveView.as_view(), name='register_active'),
	path('reset/<url_reset_code>', ResetPsdView.as_view(), name='resetpwd'),
	path('forgetpwd/', ForgetpwdView.as_view(), name='forgetpwd'),
	path('modifypwd/', ModifyPsdView.as_view(), name='modifypwd'),
	# 个人中心-个人信息页
	path('info/', UserInfoView.as_view(), name='user_info'),
	path('image/upload/', UploadImageView.as_view(), name='user_upload_image'),
	path('update/pwd/', UpdatePwdView.as_view(), name='user_update_pwd'),
	path('sendemail_code/', SendEmailCodeView.as_view(), name='sendemail_code'),
	path('update_email/', UpdateEmailView.as_view(), name='user_update_email'),
	path('updatepro/', UpdateUserProfileView.as_view(), name='user_update_profile'),
	# 个人中心 -我的课程
	path('course/', MycourseView.as_view(), name='user_course'),
	# 个人中心- 我的收藏
	path('fav_org/', MyFavOrgView.as_view(), name='user_fav_org'),
	path('fav_course/', MyFavCourseView.as_view(), name='user_fav_course'),
	path('fav_teacher/', MyFavTeacherView.as_view(), name='user_fav_teacher'),
	# 个人中心 - 我的消息
	path('my_message/', UserMessageView.as_view(), name='user_message'),
]

extra_apps/DjangoUeditor3-master/DUSite/urls.py
#coding:utf-8
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
import settings
from django.contrib import admin
from TestApp.views import  TestUEditorModel,ajaxcmd,TestUEditor

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DUSite.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^test/$',TestUEditorModel),
    url(r'^test2/$',TestUEditor),
    url(r'^ajaxcmd/$',ajaxcmd)

)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
        url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
        url(r'^(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    )

extra_apps/DjangoUeditor3-master/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

muxue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.static import serve  # 处理静态文件
from django.conf.urls import url
from django.views.generic import TemplateView
import xadmin

from users.views import TestView, IndexView

urlpatterns = [

	path('xadmin/', xadmin.site.urls),
	path('test/', TestView.as_view(), name='test'),
	path("", IndexView.as_view(), name='index'),
	# 验证码路由
	path('captcha/', include('captcha.urls')),

	# 用户组
	path('users/', include(('users.urls', 'users'), namespace='users')),

	# 机构组路由
	path('org/', include(('organization.urls', 'organization'), namespace='org')),

	# 课程路由
	path('course/', include(('courses.urls', 'courses'), namespace='course')),

	# 富文本编辑器
	url(r'^ueditor/',include('DjangoUeditor.urls' )),

	# 静态文件路由
	url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
	url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

if settings.DEBUG:
	urlpatterns.append(url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}))

# 全局页面配置
handler403 = 'users.views.page_not_look'
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/courses/models.py
# _*_ encoding:utf-8 _*_
from datetime import datetime

from django.db import models

from organization.models import CourseOrg, Teacher
from DjangoUeditor.models import UEditorField


# Create your models here.

class Course(models.Model):
	tag = models.CharField(max_length=100, default='python', verbose_name='课程类别')
	course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, null=True, verbose_name='所属机构')
	course_Teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True, verbose_name='授课教师')
	name = models.CharField(max_length=50, verbose_name=u"课程名称")
	desc = UEditorField(verbose_name='课程详情', width=600, height=300, toolbars="full", imagePath="course/ueditor",
						  filePath="course/ueditor",
						  default='')
	detail = models.CharField(verbose_name='课程描述',max_length=200,default='')
	degree = models.CharField(choices=(("cj", u"初级"), ("zj", u"中级"), ("gj", u"高级")), max_length=10,
							  verbose_name=u"课程难度")
	learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟)")
	students = models.IntegerField(default=0, verbose_name=u"学习人数")
	fav_nums = models.IntegerField(default=0, verbose_name=u"收藏人数")
	image = models.ImageField(upload_to="courses/%Y/%m", verbose_name=u"封面", default='default.png')
	click_nums = models.IntegerField(default=0, verbose_name=u"点击数")
	add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")
	is_banner = models.BooleanField(default=False, verbose_name=u'是否轮播')
	need_know = models.CharField(max_length=300, default='', verbose_name='课程须知')
	tell_you = models.CharField(max_length=300, default='好好学习', verbose_name='老师告诉你什么')

	class Meta:
		verbose_name = u"课程"
		verbose_name_plural = verbose_name

	def get_lesson_nums(self):
		return self.lesson_set.count()

	get_lesson_nums.short_description = '章节数'

	def get_lesson(self):
		return self.lesson_set

	def __str__(self):
		return self.name


class BannerCourse(Course):
	class Meta:
		verbose_name = "轮播课程"
		verbose_name_plural = verbose_name
		proxy = True


class Lesson(models.Model):
	course = models.ForeignKey(Course, verbose_name=u"课程", on_delete=models.CASCADE)
	name = models.CharField(max_length=100, verbose_name=u"章节名")
	add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

	class Meta:
		verbose_name = u"章节"
		verbose_name_plural = verbose_name

	def get_video(self):
		return self.video_set

	def __str__(self):
		return self.name


class Video(models.Model):
	Lesson = models.ForeignKey(Lesson, verbose_name=u"章节", on_delete=models.CASCADE)
	name = models.CharField(max_length=100, verbose_name=u"视频名")
	add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")
	file = models.FileField(upload_to='Video/%Y/%m', verbose_name='视频文件')
	url = models.CharField(default='', max_length=200, verbose_name='视频文件路径')

	class Meta:
		verbose_name = u"视频"
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name


class CourseResource(models.Model):
	course = models.ForeignKey(Course, verbose_name=u"课程", on_delete=models.CASCADE)
	name = models.CharField(max_length=100, verbose_name=u"名称")
	download = models.FileField(upload_to="courses/resource/%Y/%m", verbose_name=u"资源下载")
	add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

	class Meta:
		verbose_name = u"资源下载"
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name

templates/base.html
{% load staticfiles %}
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>
        欢迎访问在线学习网——{% block title %}{% endblock %}
    </title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/muke/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
    {% block custom_css %}{% endblock %}

    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />

</head>
<body>

<section class="headerwrap ">
    <header>
		<div  class="header ">
 			<div class="top">
				<div class="wp">
					<div class="fl"><p>服务电话：<b>88888888</b></p></div>

					<!--验证是否已登录-->
                    {% if request.user.is_authenticated %}
{#登录后跳转#}
						<div class="personal">
                            <dl class="user fr">
                                <dd>{{ request.user.nick_name }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ request.user.nick_name }}</h2>
	                                    <p>{{ request.user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'users:logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
{#未登录显示#}
                        <a style="color:white" class="fr registerbtn" href="{% url 'users:register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'users:login' %}">登录</a>
                    {% endif %}
                    <a href="{% url 'users:user_message' %}">
                            <div class="msg-num"><span id="MsgNum">{{ request.user.get_unread_nums }}</span></div>
                    </a>
				</div>
			</div>
{#搜索功能#}
            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img width="350" height="100" src="{% static 'images/logo.png' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                                {% if request.path|slice:'17' == '/org/teacher/list' %}
                                    <span class="selectOption" id="jsSelectOption" data-value="teacher">授课教师</span>
                                    {% elif request.path|slice:'9' == '/org/list' %}
                                    <span class="selectOption" id="jsSelectOption" data-value="org">课程机构</span>
                                    {% else %}
                                    <span class="selectOption" id="jsSelectOption" data-value="course">公开课</span>
                                {% endif %}
                                
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课教师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="{% if request.GET.keywords %}{{ request.GET.keywords }}{% endif %}" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>

			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li class="{% ifequal request.path '/' %}active{% endifequal %}" >
                                <a href="{% url 'index' %}">首页</a>
                            </li>
							<li class="{% ifequal request.path|slice:'7' '/course' %}active{% endifequal %}">
								<a href="{% url 'course:course_list' %}">公开课<img class="hot" src="{% static 'images/nav_hot.png' %}"></a>
							</li>
							<li class="{% ifequal request.path|slice:'17' '/org/teacher/list' %}active{% endifequal %}">
								<a href="{% url 'org:teacher_list' %}">授课教师</a>
							</li>
							<li class="{% ifequal request.path|slice:'9' '/org/list' %}active{% endifequal %}">
                                <a href="{% url 'org:org_list' %}">授课机构</a>
                            </li>
						</ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
</section>

<!--sidebar start-->
<section>
    <ul class="sidebar" >
        <li class="qq" title="QQ联系">
            <a target="_blank" href="http://shang.qq.com/email/stop/email_stop.html?qq=864443695&sig=398f693a80c4ed602a45372b5c1b5f7045f2b87a66326341&tttt=1"></a>
        </li>
        <li class="totop" title="返回顶部">
            <a href="#"></a>
        </li>
    </ul>
</section>
<!--sidebar end-->
{% block crumbs%} {% endblock %}
{% block body %}{% endblock %}

<footer>
		<div class="footer">
            <div class="wp">
				<ul class="cont">
					<li class=""><a href="#"><img src="{% static 'images/logo.png' %}"/></a></li>
					<li class="code"><img src="{% static 'images/code.jpg' %}"/><p class="center">扫描关注微信</p></li>
					<li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/><p class="tell">88888888</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>
			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">2018 http://52.193.67.154 在线学习交流平台 保留所有权利</span>
                <span class="fr" >copyright  2018 ICP备案证书号：京ICP备xxxxx号-1</span>
			</div>
		</div>
</footer>



<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>

{#使用jQuery库#}
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>

{% block custom_js %} {% endblock %}

</body>
</html>

templates/index.html
<!DOCTYPE html>{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}公开课列表{% endblock %}

{% block crumbs %}{% endblock %}

{% block body %}
    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
                            {% for banner in banners %}
                            <li>
                                    <a href="{{ banner.url }}">
                                        <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
                            {% endfor %}
						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="{% static 'images/feature1.png' %}"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="{% static 'images/feature2.png' %}"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="{% static 'images/feature3.png' %}"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="{% static 'images/feature3.png' %}"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
                                {% for banner in banner_course %}
                                    <li>
                                        <a href="{% url 'course:course_detail' banner.id %}">
                                            <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                        </a>
                                    </li>
                                {% endfor %}
								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                            {% for course in courses %}
                                <div class="module1_{{ forloop.counter|add:2 }} box">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                    </a>
                                    <div class="des">
                                        <a href="{% url 'course:course_detail' course.id %}">
                                            <h2 title="{{ course.name }}">{{ course.name }}</h2>
                                        </a>
                                        <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                        <span class="fr">学习人数：{{ course.students }}</span>
                                    </div>
                                    <div class="bottom">
                                        <span class="fl" title="慕课网">{{ course.course_org.name }}</span>
                                        <span class="star fr">{{ course.fav_nums }}</span>
                                    </div>
                                </div>
                            {% endfor %}
					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="{% static 'images/module3_1.jpg' %}"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
                            {% for org in orgs %}
{#                                <li class="{% if forloop.counter|divisibleby : 5 %}five{% endif %}">#}
                                <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
                                    <a href="{% url 'org:org_home' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="{{ org.name }}">{{ org.name }}</span></p>
                                    </a>
                                </li>

                            {% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

{% block custom_js %}
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/password_reset.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'users:modifypwd' %}" method="post">
            <ul>
                <input type="hidden", name="email", value="{{ email }}">
                <input type="hidden", name="url_reset_code", value="{{ url_reset_code }}">
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <div>
                    {% for key,errors in modify_form.errors.items %}
                        {{ errors }}
                    {% endfor %}
                    {{ msg }}
                </div>
                <li class="button">
                    <input type="submit" value="提交" >
                </li>
            </ul>
        {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="{% static 'images/check2.png' %}">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

templates/reset_failed.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>激活邮件发送失败</title>
</head>
<body>
<p>激活链接失败，请重试</p>
</body>
</html>

templates/usercenter-fav-org.html
{% extends 'base_usercenter.html' %}
{% load staticfiles %}
{% block title %}
个人信息--慕学在线网
{% endblock %}
{% block crumbs %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:user_fav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'users:user_fav_teacher' %}">授课教师 </a></li>
                        <li><a href="{% url 'users:user_fav_course' %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for fav_org in fav_orgs.object_list %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_desc' fav_org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ fav_org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="org-detail-homepage.html">{{ fav_org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ fav_org.city }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ fav_org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                <div class="pageturn">
                <ul class="pagelist">
                {% if fav_orgs.has_previous %}
                    <li class="long"><a href="?{{ fav_orgs.previous_page_number.querystring }}" class="prev">上一页</a></li>
                {% endif %}
{#                <li class="active"><a class="page" href="?page=2">2</a></li>#}
{#                <li class="active"><a href="?page=1">1</a></li>#}
{#            不能＋class==page 不然微了#}
                {% for page in fav_orgs.pages %}
                    {% if page %}
                        {% ifequal page fav_orgs.number %}
                            <li class="active"><a href="?{{ page.querystring }}" >{{ page }}</a></li>
                        {% else %}
                            <li><a href="?{{ page.querystring }}" >{{ page }}</a></li>
                        {% endifequal %}
                    {% else %}
                        <li class="none"><a href="">...</a></li>
                    {% endif %}
                {% endfor %}
                {% if fav_orgs.has_next %}
                    <li class="long"><a href="?{{ fav_orgs.next_page_number.querystring }}">下一页</a></li>
                {% endif %}
            </ul>
            </div>
                </div>

            </div>
        </div>
{% endblock %}